# Upstream changes from _extends are only recognized when modifications are made to this file in the default branch.
_extends: .github
repository:
  name: aws-sqs-queue
  description: This component is responsible for creating an SQS queue
  homepage: https://cloudposse.com/accelerate
  topics: terraform, terraform-component






